#!groovy
@Library('jenkinslib') _

def build = new org.devops.build()
def deploy = new org.devops.deploy()

String srcUrl = "${env.srcUrl}"
String branchName = "${env.branchName}"
String buildType = "${env.buildType}"
String buildShell = "${env.buildShell}"
//String func = "${env.func}"
//String hosts = "${env.hosts}"
pipeline {
    agent {node {label "master"}}
    
    stages{
        stage("checkout"){
            steps{
                script{
                    checkout([$class: 'GitSCM', branches: [[name: "${branchName}"]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'jenkinsforgithub', url: "${srcUrl}"]]])
                }
            }
        }
    }
    
    stages{
        stage("build"){
            steps{
                script{
                    build.Build(buildType,buildShell)
                }
            }
        }
        
        /*stage("deploy"){
            steps{
                script{
                    deploy.ansibleDeploy(hosts,func)
                }
            }
        }
        /*stage("gradlebuild"){
            steps{
                script{
                    gradleHome = tool "GRADLE"
                    sh "${gradleHome}/bin/gradle ${choice}"
                }
            }
        }
        stage("npmbuild"){
            steps{
                script{
                    npmHome = tool "NPM"
                    sh "export NODEJS_HOME=/data/devops/node-v12.18.4-linux-x64 && export PATH=\$PATH:\$NODEJS_HOME/bin && ${npmHome}/bin/npm ${choice}"
                }
            }
        }*/
    }
}
